##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Thu Apr 16 15:52:55 MSK 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = POWER_Controller

# Use bash so `set -o pipefail` works in lint recipes below: we pipe
# clang-tidy through a filter and must not lose the real exit code.
SHELL := /bin/bash


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/adc.c \
Core/Src/dma.c \
Core/Src/iwdg.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/stm32f0xx_it.c \
Core/Src/stm32f0xx_hal_msp.c \
Services/adc_service.c \
Services/input_service.c \
Services/power_manager.c \
Services/fault_manager.c \
Services/flash_cal.c \
Services/bootloader.c \
Protocol/uart_protocol.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_exti.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c \
Drivers/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.c \
Core/Src/system_stm32f0xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f030x8.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F030x8


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F0xx_HAL_Driver/Inc \
-IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F0xx/Include \
-IDrivers/CMSIS/Include \
-IConfig \
-IServices \
-IProtocol


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F030XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

#######################################
# LINT (static analysis)
# Scope: user code (Core/Src + Services + Protocol) + Tests.
# HAL/CMSIS sources are NOT analyzed, only included for symbol resolution.
#
# Targets:
#   make lint            — run all checks (warnings + cppcheck + clang-tidy)
#   make warnings-check  — arm-none-eabi-gcc strict warnings (-fsyntax-only)
#   make cppcheck        — cppcheck on user code + tests
#   make tidy            — clang-tidy on user code + tests
#   make lint-install    — apt install clang-tidy + cppcheck (sudo)
#
# Hard mode: any linter finding returns non-zero (ci-friendly).
# Main build (`make all`) is unaffected.
#######################################

# Only main.c from Core/Src is linted: the rest of Core/Src is CubeMX-generated
# glue (gpio.c, adc.c, dma.c, iwdg.c, tim.c, usart.c, stm32f0xx_it.c,
# stm32f0xx_hal_msp.c) per Rules_POWER.md ("all peripheral changes via .ioc").
# Those files are regenerated by CubeMX and are not our code.
LINT_USER_SRCS = \
  Core/Src/main.c \
  Services/adc_service.c \
  Services/input_service.c \
  Services/power_manager.c \
  Services/fault_manager.c \
  Services/flash_cal.c \
  Services/bootloader.c \
  Protocol/uart_protocol.c

LINT_TEST_SRCS = $(wildcard Tests/test_*.c)

# User-code include paths: analyzed by all linters (-I).
LINT_USER_INCLUDES = \
  -ICore/Inc \
  -IConfig -IServices -IProtocol

# HAL/CMSIS include paths. Two variants:
#   LINT_SYS_INCLUDES          — plain -I, used by gcc (warnings-check) and
#                                cppcheck (it has its own --suppress=*:Drivers/*).
#   LINT_SYS_INCLUDES_ISYSTEM  — -isystem form, used ONLY by clang-tidy.
# With -isystem, clang marks HAL/CMSIS as system headers, which makes
# clang-tidy's default policy ("suppress diagnostics from system headers")
# drop every HAL finding from the output. HeaderFilterRegex in .clang-tidy
# is the second line of defense for anything slipping through.
# NB: on LLVM 14 the static-analyzer still traverses the HAL AST and
# internally counts those diagnostics ("N warnings generated."); we strip
# that chatter in CLANG_TIDY_FILTER. Actual emitted findings are 0.
LINT_SYS_INCLUDES = \
  -IDrivers/STM32F0xx_HAL_Driver/Inc \
  -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy \
  -IDrivers/CMSIS/Device/ST/STM32F0xx/Include \
  -IDrivers/CMSIS/Include

LINT_SYS_INCLUDES_ISYSTEM = \
  -isystem Drivers/STM32F0xx_HAL_Driver/Inc \
  -isystem Drivers/STM32F0xx_HAL_Driver/Inc/Legacy \
  -isystem Drivers/CMSIS/Device/ST/STM32F0xx/Include \
  -isystem Drivers/CMSIS/Include

# Back-compat alias: aggregates user + HAL includes with -I (used by gcc/cppcheck).
LINT_INCLUDES = $(LINT_USER_INCLUDES) $(LINT_SYS_INCLUDES)

LINT_DEFS = -DUSE_HAL_DRIVER -DSTM32F030x8

LINT_TEST_INCLUDES = -ITests/stubs -ITests/unity -I.
LINT_TEST_DEFS     = -DUNIT_TEST

# -------- cppcheck --------
# NOTE: -D__GNUC__=11 tells cppcheck we build with arm-none-eabi-gcc,
# so cmsis_compiler.h selects the GCC branch instead of hitting
# "#error Unknown compiler". Drivers/* findings are suppressed because
# HAL/CMSIS sources are only included for symbol resolution, not analyzed.
CPPCHECK       ?= cppcheck
CPPCHECK_FLAGS  = --enable=warning,style,performance,portability \
                  --std=c11 --platform=unix32 \
                  --inline-suppr \
                  -D__GNUC__=11 \
                  --suppress=missingInclude \
                  --suppress=missingIncludeSystem \
                  --suppress=unusedFunction \
                  --suppress=unmatchedSuppression \
                  --suppress=ConfigurationNotChecked \
                  --suppress=*:Drivers/* \
                  --quiet \
                  --error-exitcode=1

# -------- clang-tidy --------
# HAL/CMSIS paths are mounted via -isystem (see LINT_SYS_INCLUDES_ISYSTEM) so
# clang-tidy's HeaderFilterRegex + "diagnostics from system headers are
# suppressed by default" policy act together to drop 100% of HAL findings
# from the output. `make tidy` ends with 0 emitted findings unless user code
# genuinely has a hit.
#
# Note on LLVM 14 limitation: clang static-analyzer checkers still traverse
# HAL/CMSIS AST and *generate* diagnostics internally; they are filtered
# out before display. This shows up as informational lines like
# "N warnings generated." / "Suppressed N warnings (N in non-user code)."
# which we strip in the tidy target below. The only way to stop generation
# entirely is `ExcludeHeaderFilterRegex` (added in LLVM 19) — not available
# on Ubuntu 22.04's clang-tidy 14.
CLANG_TIDY       ?= clang-tidy
CLANG_TIDY_FLAGS = --warnings-as-errors=* --quiet
# Extra args passed to the underlying clang parser:
CLANG_TIDY_COMPILE = -std=gnu11 \
                     -Wno-unknown-attributes -Wno-unknown-pragmas \
                     -Wno-gnu-zero-variadic-macro-arguments

# Informational chatter clang-tidy prints even when every finding is
# suppressed. Stripping them keeps `make lint` output signal-only.
# Real findings use "path:line:col: error:" and never match these patterns.
# `sed` (not grep) is intentional: sed always exits 0, so `set -o pipefail`
# below can still detect a real clang-tidy failure upstream in the pipe.
CLANG_TIDY_FILTER = sed -E \
    -e '/^[0-9]+ warnings generated\.$$/d' \
    -e '/^Suppressed [0-9]+ warnings.*$$/d' \
    -e '/^Use -header-filter=.*$$/d'

# -------- strict warnings (arm-none-eabi-gcc, -fsyntax-only) --------
WARN_CC         ?= $(CC)
WARN_MCU         = $(MCU)
WARN_CFLAGS      = $(WARN_MCU) -std=gnu11 -fsyntax-only \
                   -Wall -Wextra -Wpedantic \
                   -Wshadow -Wundef -Wpointer-arith \
                   -Wstrict-prototypes -Wmissing-prototypes \
                   -Wredundant-decls \
                   -Wwrite-strings -Wformat=2 \
                   -Werror
# NOTE: -Wcast-align is intentionally omitted — STM32 HAL DMA APIs
# routinely take (uint32_t *) on byte-aligned buffers, producing
# false positives under Cortex-M0 strict-align.

.PHONY: lint tidy cppcheck warnings-check lint-install

lint-install:
	@echo ">>> Installing clang-tidy and cppcheck (sudo required)..."
	sudo apt-get update && sudo apt-get install -y clang-tidy cppcheck

warnings-check:
	@echo ">>> [warnings-check] arm-none-eabi-gcc strict warnings on user code"
	@set -e; for f in $(LINT_USER_SRCS); do \
		echo "   -- $$f"; \
		$(WARN_CC) $(WARN_CFLAGS) $(LINT_DEFS) $(LINT_INCLUDES) $$f ; \
	done
	@echo ">>> [warnings-check] OK"

cppcheck:
	@echo ">>> [cppcheck] user code"
	$(CPPCHECK) $(CPPCHECK_FLAGS) $(LINT_DEFS) $(LINT_INCLUDES) $(LINT_USER_SRCS)
	@echo ">>> [cppcheck] tests"
	$(CPPCHECK) $(CPPCHECK_FLAGS) $(LINT_TEST_DEFS) $(LINT_TEST_INCLUDES) \
	            -IConfig -IServices -IProtocol $(LINT_TEST_SRCS)
	@echo ">>> [cppcheck] OK"

tidy:
	@echo ">>> [clang-tidy] user code"
	@set -e -o pipefail; for f in $(LINT_USER_SRCS); do \
		echo "   -- $$f"; \
		$(CLANG_TIDY) $(CLANG_TIDY_FLAGS) $$f -- \
		    $(CLANG_TIDY_COMPILE) $(LINT_DEFS) \
		    $(LINT_USER_INCLUDES) $(LINT_SYS_INCLUDES_ISYSTEM) \
		    2>&1 | $(CLANG_TIDY_FILTER) ; \
	done
	@echo ">>> [clang-tidy] tests"
	@set -e -o pipefail; for f in $(LINT_TEST_SRCS); do \
		echo "   -- $$f"; \
		$(CLANG_TIDY) $(CLANG_TIDY_FLAGS) $$f -- \
		    $(CLANG_TIDY_COMPILE) $(LINT_TEST_DEFS) $(LINT_TEST_INCLUDES) \
		    -IConfig -IServices -IProtocol \
		    2>&1 | $(CLANG_TIDY_FILTER) ; \
	done
	@echo ">>> [clang-tidy] OK"

lint: warnings-check cppcheck tidy
	@echo ">>> [lint] All checks passed."

# *** EOF ***
