# Настройки UART-тестов с подключённой периферией (дисплей, без Q7).
# Переопределение: UART_DEVICE=/dev/ttyACM0 ./run_all_peripheral.sh

UART_DEVICE="${UART_DEVICE:-/dev/ttyUSB0}"
UART_BAUD=115200

BOOT_PING_RETRIES="${BOOT_PING_RETRIES:-60}"
BOOT_PING_INTERVAL_SEC="${BOOT_PING_INTERVAL_SEC:-0.5}"
UART_POST_OPEN_DELAY_SEC="${UART_POST_OPEN_DELAY_SEC:-0.5}"

ACK_TIMEOUT_SEC=0.5
GET_STATUS_TIMEOUT_SEC=1.0
GET_STATUS_TX_DELAY_SEC=0.35
POWER_CTRL_TX_DELAY_SEC=0.25

GET_STATUS_FRAME_LEN=31
ACK_FRAME_LEN=6

# Секвенсинг дисплея: шаги 1–6 ~500–700 мс; запас на verify + опрос
SEQ_ON_WAIT_SEC="${SEQ_ON_WAIT_SEC:-2.0}"
SEQ_BL_WAIT_SEC="${SEQ_BL_WAIT_SEC:-0.6}"
SEQ_DN_WAIT_SEC="${SEQ_DN_WAIT_SEC:-1.2}"
AUDIO_SEQ_WAIT_SEC="${AUDIO_SEQ_WAIT_SEC:-0.25}"

STATE_POLL_INTERVAL_SEC="${STATE_POLL_INTERVAL_SEC:-0.1}"
STATE_POLL_TRIES="${STATE_POLL_TRIES:-40}"

# Пороги шин (мВ) — как Tests_UART / config.h
THRESH_V12_MIN_MV=10000
THRESH_V12_MAX_MV=13000
THRESH_V5_MIN_MV=4500
THRESH_V5_MAX_MV=5500
THRESH_V3V3_MIN_MV=3000
THRESH_V3V3_MAX_MV=3600

# Токи под нагрузкой (мА)
LOAD_I_MIN_MA="${LOAD_I_MIN_MA:-5}"
LOAD_I_MAX_MA="${LOAD_I_MAX_MA:-3200}"
LOAD_I_CHANNELS="${LOAD_I_CHANNELS:-i_lcd,i_backlight,i_scaler}"

# Калибровка нуля (state=0)
TELEMETRY_I_ZERO_MIN_MA=-200
TELEMETRY_I_ZERO_MAX_MA=200

# Блок 3: ловушка I_LCD
THRESH_I_LCD_DEFAULT_MA=2000
THRESH_I_LCD_TRAP_MA="${THRESH_I_LCD_TRAP_MA:-50}"
FAULT_LCD_FLAG=0x0002
SET_THRESH_TX_DELAY_SEC=0.2
FAULT_POLL_INTERVAL_SEC=0.1
FAULT_WAIT_TRIES="${FAULT_WAIT_TRIES:-40}"

# SET_BRIGHTNESS
BRIGHTNESS_MID="${BRIGHTNESS_MID:-500}"
BRIGHTNESS_MAX="${BRIGHTNESS_MAX:-1000}"
BRIGHTNESS_MIN="${BRIGHTNESS_MIN:-0}"

CALIBRATE_OFFSET_TIMEOUT_SEC=3.0

# Секвенс SCALER: FAULT_SEQ_ABORT|FAULT_SCALER — блокирует зависимые display-тесты в run_all
FAULT_DISPLAY_SEQ_BLOCK=0x2001
DISPLAY_SKIP_REASON="${DISPLAY_SKIP_REASON:-SCALER sequence verify failed (fault 0x2001): check ~12 V at scaler and SCALER_POWER_M (PB1), SEQ_VERIFY_SCALER_MV=4000}"

# Блок 6: ручная проверка SUS_S3# / PWRBTN#
# RUN_SUS_S3_HW_TEST=1 — не пропускать шаг в run_all (всё равно без LA только инструкции)
RUN_SUS_S3_HW_TEST="${RUN_SUS_S3_HW_TEST:-0}"

STRESS_GET_STATUS_COUNT=20
STRESS_GET_STATUS_INTERVAL_SEC=0.05
PACKET_TIMEOUT_PAUSE_MS=60
INTERBYTE_GAP_MS=15
NO_RESPONSE_TIMEOUT_SEC=0.25
IWDG_STRESS_COUNT=20
IWDG_STRESS_INTERVAL_SEC=0.1

FAULT_V12_TRAP_MIN_MV=13000
FAULT_V12_TRAP_MAX_MV=14000
FAULT_V5_TRAP_MIN_MV=5600
FAULT_V5_TRAP_MAX_MV=5800
FAULT_V3V3_TRAP_MIN_MV=3600
FAULT_V3V3_TRAP_MAX_MV=3700
FAULT_MONITOR_ARM_SEC=0.15
FAULT_WAIT_TRIES_VOLT=30
