# BVIT UART tests for Q7 Linux (socat → /dev/ttyS0).
# Override: UART_DEVICE=/dev/ttyS0 ./run_all.sh

UART_DEVICE="${UART_DEVICE:-/dev/ttyS0}"
UART_BAUD="${UART_BAUD:-115200}"

BOOT_PING_RETRIES="${BOOT_PING_RETRIES:-60}"
BOOT_PING_INTERVAL_SEC="${BOOT_PING_INTERVAL_SEC:-0.5}"
UART_POST_OPEN_DELAY_SEC="${UART_POST_OPEN_DELAY_SEC:-0.1}"

ACK_TIMEOUT_SEC="${ACK_TIMEOUT_SEC:-1.0}"
# BOOTLOADER_ENTER ACK is deferred until graceful DN finishes (~50–100 ms).
OTA_BOOTLOADER_ACK_TIMEOUT_SEC="${OTA_BOOTLOADER_ACK_TIMEOUT_SEC:-2.0}"
GET_STATUS_TIMEOUT_SEC="${GET_STATUS_TIMEOUT_SEC:-1.5}"
GET_STATUS_TX_DELAY_SEC="${GET_STATUS_TX_DELAY_SEC:-0.35}"
POWER_CTRL_TX_DELAY_SEC="${POWER_CTRL_TX_DELAY_SEC:-0.25}"

GET_STATUS_FRAME_LEN=27
GET_VERSION_FRAME_LEN=18
ACK_FRAME_LEN=6

SEQ_ON_WAIT_SEC="${SEQ_ON_WAIT_SEC:-2.0}"
SEQ_BL_WAIT_SEC="${SEQ_BL_WAIT_SEC:-4.0}"
SEQ_DN_WAIT_SEC="${SEQ_DN_WAIT_SEC:-1.2}"
AUDIO_SEQ_WAIT_SEC="${AUDIO_SEQ_WAIT_SEC:-0.25}"

PERIPH_AUDIO_HW_ENABLED="${PERIPH_AUDIO_HW_ENABLED:-0}"
PERIPH_TOUCH_HW_ENABLED="${PERIPH_TOUCH_HW_ENABLED:-0}"
PERIPH_BL_CURRENT_SENSOR_ENABLED="${PERIPH_BL_CURRENT_SENSOR_ENABLED:-0}"
TELEMETRY_I_CHANNELS="${TELEMETRY_I_CHANNELS:-i_lcd,i_scaler,i_audio_l,i_audio_r}"

STATE_POLL_INTERVAL_SEC="${STATE_POLL_INTERVAL_SEC:-0.1}"
STATE_POLL_TRIES="${STATE_POLL_TRIES:-40}"

PERIPH_PREP_NONDISPLAY_MASK_HEX="${PERIPH_PREP_NONDISPLAY_MASK_HEX:-0x48}"
STATE_ETH_ALWAYS_ON_HEX="${STATE_ETH_ALWAYS_ON_HEX:-0x30}"
STATE_MANAGED_OFF_CLEAR_MASK_HEX="${STATE_MANAGED_OFF_CLEAR_MASK_HEX:-0x4f}"

THRESH_V12_MIN_MV=10000
THRESH_V12_MAX_MV=13000
THRESH_V5_MIN_MV=4500
THRESH_V5_MAX_MV=5500
THRESH_V3V3_MIN_MV=3000
THRESH_V3V3_MAX_MV=3600

LOAD_I_MIN_MA="${LOAD_I_MIN_MA:-5}"
LOAD_I_MAX_MA="${LOAD_I_MAX_MA:-3200}"
LOAD_I_CHANNELS="${LOAD_I_CHANNELS:-i_lcd,i_scaler}"

TELEMETRY_I_ZERO_MIN_MA=-200
TELEMETRY_I_ZERO_MAX_MA=200

THRESH_I_LCD_DEFAULT_MA=2000
THRESH_I_BL_DEFAULT_MA=3000
THRESH_I_SCALER_DEFAULT_MA=1500
THRESH_I_AUDIO_DEFAULT_MA=800
THRESH_I_LCD_TRAP_MA="${THRESH_I_LCD_TRAP_MA:-50}"
THRESH_I_BL_TRAP_MA="${THRESH_I_BL_TRAP_MA:-50}"
THRESH_I_SCALER_TRAP_MA="${THRESH_I_SCALER_TRAP_MA:-50}"
THRESH_I_AUDIO_TRAP_MA="${THRESH_I_AUDIO_TRAP_MA:-50}"
THRESH_I_TRAP_MARGIN_MA="${THRESH_I_TRAP_MARGIN_MA:-15}"
THRESH_I_TRAP_MIN_LOAD_MA="${THRESH_I_TRAP_MIN_LOAD_MA:-25}"

FAULT_LCD_FLAG=0x0002
FAULT_SCALER_FLAG=0x0001
FAULT_BACKLIGHT_FLAG=0x0004
FAULT_AUDIO_FLAG=0x0008
FAULT_V12_RANGE_FLAG=0x0400
FAULT_V5_RANGE_FLAG=0x0800
FAULT_V3V3_RANGE_FLAG=0x1000
FAULT_PGOOD_LOST_FLAG=0x0080
FAULT_SEQ_ABORT_FLAG=0x2000
SET_THRESH_TX_DELAY_SEC=0.2
FAULT_POLL_INTERVAL_SEC=0.1
FAULT_WAIT_TRIES="${FAULT_WAIT_TRIES:-40}"

BRIGHTNESS_MID="${BRIGHTNESS_MID:-500}"
BRIGHTNESS_MAX="${BRIGHTNESS_MAX:-1000}"
BRIGHTNESS_MIN="${BRIGHTNESS_MIN:-0}"

CALIBRATE_OFFSET_TIMEOUT_SEC=3.0

FAULT_DISPLAY_SEQ_BLOCK=0x2001
DISPLAY_SKIP_REASON="${DISPLAY_SKIP_REASON:-SCALER sequence verify failed (fault 0x2001): check ~12 V at scaler and SCALER_POWER_M (PB1), SEQ_VERIFY_SCALER_MV=4000}"

RUN_SUS_S3_HW_TEST="${RUN_SUS_S3_HW_TEST:-0}"
RUN_PGOOD_MID_SEQ_HW_TEST="${RUN_PGOOD_MID_SEQ_HW_TEST:-0}"

# OTA / pending-confirm (scripts 34–35; not in run_all by default)
OTA_STM32FLASH="${OTA_STM32FLASH:-stm32flash}"
OTA_FLASH_ADDR="${OTA_FLASH_ADDR:-0x08000000}"
OTA_RESET_DELAY_SEC="${OTA_RESET_DELAY_SEC:-0.5}"
OTA_NRST_SETTLE_SEC="${OTA_NRST_SETTLE_SEC:-1}"
# Optional: shell command for IC17 NRST pulse (no BOOT0) — application reboot only
OTA_NRST_CMD="${OTA_NRST_CMD:-}"
# Default firmware path on Q7 after scp (override with FW_BIN=...)
FW_BIN="${FW_BIN:-/tmp/POWER_Controller.bin}"

STRESS_GET_STATUS_COUNT=20
STRESS_GET_STATUS_INTERVAL_SEC=0.05
IWDG_STRESS_COUNT=20
IWDG_STRESS_INTERVAL_SEC=0.1

FAULT_V12_TRAP_MIN_MV=13000
FAULT_V12_TRAP_MAX_MV=14000
FAULT_V5_TRAP_MIN_MV=5600
FAULT_V5_TRAP_MAX_MV=5800
FAULT_V3V3_TRAP_MIN_MV=3600
FAULT_V3V3_TRAP_MAX_MV=3700
FAULT_MONITOR_ARM_SEC=0.15
FAULT_WAIT_TRIES_VOLT=30
PERIPH_BACKLIGHT_ON_TRIES="${PERIPH_BACKLIGHT_ON_TRIES:-3}"
